name: CI/CD - Build, Secure & Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build-secure-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run tests
        run: npm run test || echo "No tests yet"

      - name: Trivy Vulnerability Scan (Filesystem + NPM)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          format: table
          exit-code: 0
          vuln-type: library
          scan-ref: .

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=omarfrikha96_Portfolio
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.organization=omarfrikha96
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Build the app
        run: npm run build

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1 

      - name: Deploy to S3
        run: |
          aws s3 sync build/ s3://omarportfolioweb  --delete --exclude ".git/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}